"""initial schema

Revision ID: 0b81611fb611
Revises: 
Create Date: 2026-05-20 22:15:41.970634
"""
from alembic import op
import sqlalchemy as sa



revision = '0b81611fb611'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('alert_type', sa.String(length=128), nullable=False),
    sa.Column('src_ip', sa.String(length=64), nullable=True),
    sa.Column('dst_ip', sa.String(length=64), nullable=True),
    sa.Column('threat_score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('matched_rules_json', sa.JSON(), nullable=False),
    sa.Column('recommended_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_dst_ip'), 'alerts', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_src_ip'), 'alerts', ['src_ip'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_threat_score'), 'alerts', ['threat_score'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=128), nullable=False),
    sa.Column('target_value', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_table('blocked_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_ips_active'), 'blocked_ips', ['active'], unique=False)
    op.create_index(op.f('ix_blocked_ips_ip_address'), 'blocked_ips', ['ip_address'], unique=False)
    op.create_table('raw_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_line', sa.Text(), nullable=False),
    sa.Column('syslog_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_hostname', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_logs_device_hostname'), 'raw_logs', ['device_hostname'], unique=False)
    op.create_index(op.f('ix_raw_logs_syslog_timestamp'), 'raw_logs', ['syslog_timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('normalized_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_log_id', sa.Integer(), nullable=False),
    sa.Column('receive_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_type', sa.String(length=64), nullable=True),
    sa.Column('subtype', sa.String(length=128), nullable=True),
    sa.Column('serial', sa.String(length=128), nullable=True),
    sa.Column('src_ip', sa.String(length=64), nullable=True),
    sa.Column('dst_ip', sa.String(length=64), nullable=True),
    sa.Column('nat_src_ip', sa.String(length=64), nullable=True),
    sa.Column('nat_dst_ip', sa.String(length=64), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=True),
    sa.Column('src_user', sa.String(length=255), nullable=True),
    sa.Column('dst_user', sa.String(length=255), nullable=True),
    sa.Column('app', sa.String(length=255), nullable=True),
    sa.Column('vsys', sa.String(length=128), nullable=True),
    sa.Column('src_zone', sa.String(length=128), nullable=True),
    sa.Column('dst_zone', sa.String(length=128), nullable=True),
    sa.Column('inbound_interface', sa.String(length=128), nullable=True),
    sa.Column('outbound_interface', sa.String(length=128), nullable=True),
    sa.Column('log_action', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('repeat_count', sa.Integer(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('bytes_sent', sa.Integer(), nullable=True),
    sa.Column('bytes_received', sa.Integer(), nullable=True),
    sa.Column('packets', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elapsed_time', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('src_country', sa.String(length=255), nullable=True),
    sa.Column('dst_country', sa.String(length=255), nullable=True),
    sa.Column('packets_sent', sa.Integer(), nullable=True),
    sa.Column('packets_received', sa.Integer(), nullable=True),
    sa.Column('session_end_reason', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('action_source', sa.String(length=255), nullable=True),
    sa.Column('rule_uuid', sa.String(length=128), nullable=True),
    sa.Column('high_res_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('app_subcategory', sa.String(length=255), nullable=True),
    sa.Column('app_category', sa.String(length=255), nullable=True),
    sa.Column('app_technology', sa.String(length=255), nullable=True),
    sa.Column('app_risk', sa.Integer(), nullable=True),
    sa.Column('app_characteristic', sa.Text(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('parsed_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['raw_log_id'], ['raw_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_normalized_action_generated', 'normalized_logs', ['action', 'generated_time'], unique=False)
    op.create_index(op.f('ix_normalized_logs_action'), 'normalized_logs', ['action'], unique=False)
    op.create_index(op.f('ix_normalized_logs_app'), 'normalized_logs', ['app'], unique=False)
    op.create_index(op.f('ix_normalized_logs_app_category'), 'normalized_logs', ['app_category'], unique=False)
    op.create_index(op.f('ix_normalized_logs_app_risk'), 'normalized_logs', ['app_risk'], unique=False)
    op.create_index(op.f('ix_normalized_logs_device_name'), 'normalized_logs', ['device_name'], unique=False)
    op.create_index(op.f('ix_normalized_logs_dst_country'), 'normalized_logs', ['dst_country'], unique=False)
    op.create_index(op.f('ix_normalized_logs_dst_ip'), 'normalized_logs', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_normalized_logs_dst_port'), 'normalized_logs', ['dst_port'], unique=False)
    op.create_index(op.f('ix_normalized_logs_dst_zone'), 'normalized_logs', ['dst_zone'], unique=False)
    op.create_index(op.f('ix_normalized_logs_generated_time'), 'normalized_logs', ['generated_time'], unique=False)
    op.create_index(op.f('ix_normalized_logs_log_type'), 'normalized_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_normalized_logs_protocol'), 'normalized_logs', ['protocol'], unique=False)
    op.create_index(op.f('ix_normalized_logs_raw_log_id'), 'normalized_logs', ['raw_log_id'], unique=False)
    op.create_index(op.f('ix_normalized_logs_receive_time'), 'normalized_logs', ['receive_time'], unique=False)
    op.create_index(op.f('ix_normalized_logs_rule_name'), 'normalized_logs', ['rule_name'], unique=False)
    op.create_index(op.f('ix_normalized_logs_rule_uuid'), 'normalized_logs', ['rule_uuid'], unique=False)
    op.create_index(op.f('ix_normalized_logs_serial'), 'normalized_logs', ['serial'], unique=False)
    op.create_index(op.f('ix_normalized_logs_session_id'), 'normalized_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_normalized_logs_src_country'), 'normalized_logs', ['src_country'], unique=False)
    op.create_index(op.f('ix_normalized_logs_src_ip'), 'normalized_logs', ['src_ip'], unique=False)
    op.create_index(op.f('ix_normalized_logs_src_port'), 'normalized_logs', ['src_port'], unique=False)
    op.create_index(op.f('ix_normalized_logs_src_zone'), 'normalized_logs', ['src_zone'], unique=False)
    op.create_index(op.f('ix_normalized_logs_subtype'), 'normalized_logs', ['subtype'], unique=False)
    op.create_index('ix_normalized_src_generated', 'normalized_logs', ['src_ip', 'generated_time'], unique=False)
    op.create_table('response_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('target_ip', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('result_message', sa.Text(), nullable=False),
    sa.Column('executed_by', sa.String(length=128), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_actions_action_type'), 'response_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_response_actions_alert_id'), 'response_actions', ['alert_id'], unique=False)
    op.create_index(op.f('ix_response_actions_status'), 'response_actions', ['status'], unique=False)
    op.create_index(op.f('ix_response_actions_target_ip'), 'response_actions', ['target_ip'], unique=False)
    op.create_table('alert_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('normalized_log_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['normalized_log_id'], ['normalized_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_evidence_alert_id'), 'alert_evidence', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_evidence_normalized_log_id'), 'alert_evidence', ['normalized_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_evidence_normalized_log_id'), table_name='alert_evidence')
    op.drop_index(op.f('ix_alert_evidence_alert_id'), table_name='alert_evidence')
    op.drop_table('alert_evidence')
    op.drop_index(op.f('ix_response_actions_target_ip'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_status'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_alert_id'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_action_type'), table_name='response_actions')
    op.drop_table('response_actions')
    op.drop_index('ix_normalized_src_generated', table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_subtype'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_src_zone'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_src_port'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_src_ip'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_src_country'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_session_id'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_serial'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_rule_uuid'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_rule_name'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_receive_time'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_raw_log_id'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_protocol'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_log_type'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_generated_time'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_dst_zone'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_dst_port'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_dst_ip'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_dst_country'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_device_name'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_app_risk'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_app_category'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_app'), table_name='normalized_logs')
    op.drop_index(op.f('ix_normalized_logs_action'), table_name='normalized_logs')
    op.drop_index('ix_normalized_action_generated', table_name='normalized_logs')
    op.drop_table('normalized_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_raw_logs_syslog_timestamp'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_device_hostname'), table_name='raw_logs')
    op.drop_table('raw_logs')
    op.drop_index(op.f('ix_blocked_ips_ip_address'), table_name='blocked_ips')
    op.drop_index(op.f('ix_blocked_ips_active'), table_name='blocked_ips')
    op.drop_table('blocked_ips')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_threat_score'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_src_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dst_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
