"""add ml model run registry

Revision ID: 3efd066e772d
Revises: 67040ba97a7a
Create Date: 2026-05-20 22:47:34.103225
"""
from alembic import op
import sqlalchemy as sa



revision = '3efd066e772d'
down_revision = '67040ba97a7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('artifact_size_bytes', sa.Integer(), nullable=True),
    sa.Column('training_log_count', sa.Integer(), nullable=True),
    sa.Column('scored_log_count', sa.Integer(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=True),
    sa.Column('anomaly_rate', sa.Float(), nullable=True),
    sa.Column('contamination', sa.Float(), nullable=True),
    sa.Column('feature_columns_json', sa.JSON(), nullable=False),
    sa.Column('feature_summary_json', sa.JSON(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_model_runs_actor'), 'ml_model_runs', ['actor'], unique=False)
    op.create_index(op.f('ix_ml_model_runs_model_name'), 'ml_model_runs', ['model_name'], unique=False)
    op.create_index(op.f('ix_ml_model_runs_model_version'), 'ml_model_runs', ['model_version'], unique=False)
    op.create_index(op.f('ix_ml_model_runs_operation'), 'ml_model_runs', ['operation'], unique=False)
    op.create_index(op.f('ix_ml_model_runs_status'), 'ml_model_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_model_runs_status'), table_name='ml_model_runs')
    op.drop_index(op.f('ix_ml_model_runs_operation'), table_name='ml_model_runs')
    op.drop_index(op.f('ix_ml_model_runs_model_version'), table_name='ml_model_runs')
    op.drop_index(op.f('ix_ml_model_runs_model_name'), table_name='ml_model_runs')
    op.drop_index(op.f('ix_ml_model_runs_actor'), table_name='ml_model_runs')
    op.drop_table('ml_model_runs')
    # ### end Alembic commands ###
