"""add lab pilot controls

Revision ID: 4c6cdf517f3c
Revises: 3efd066e772d
Create Date: 2026-05-21 09:32:52.046836
"""
from alembic import op
import sqlalchemy as sa



revision = '4c6cdf517f3c'
down_revision = '3efd066e772d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppression_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_ip', sa.String(length=64), nullable=True),
    sa.Column('app', sa.String(length=255), nullable=True),
    sa.Column('alert_type', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('suppressed_count', sa.Integer(), nullable=False),
    sa.Column('last_matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('disabled_by', sa.String(length=128), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppression_rules_active'), 'suppression_rules', ['active'], unique=False)
    op.create_index(op.f('ix_suppression_rules_alert_type'), 'suppression_rules', ['alert_type'], unique=False)
    op.create_index(op.f('ix_suppression_rules_app'), 'suppression_rules', ['app'], unique=False)
    op.create_index(op.f('ix_suppression_rules_src_ip'), 'suppression_rules', ['src_ip'], unique=False)
    op.add_column('alerts', sa.Column('priority_owner', sa.String(length=128), nullable=True))
    op.add_column('alerts', sa.Column('escalation_reason', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('ticket_reference', sa.String(length=255), nullable=True))
    op.add_column('alerts', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_alerts_priority_owner'), 'alerts', ['priority_owner'], unique=False)
    op.create_index(op.f('ix_alerts_ticket_reference'), 'alerts', ['ticket_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_ticket_reference'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_priority_owner'), table_name='alerts')
    op.drop_column('alerts', 'escalated_at')
    op.drop_column('alerts', 'ticket_reference')
    op.drop_column('alerts', 'escalation_reason')
    op.drop_column('alerts', 'priority_owner')
    op.drop_index(op.f('ix_suppression_rules_src_ip'), table_name='suppression_rules')
    op.drop_index(op.f('ix_suppression_rules_app'), table_name='suppression_rules')
    op.drop_index(op.f('ix_suppression_rules_alert_type'), table_name='suppression_rules')
    op.drop_index(op.f('ix_suppression_rules_active'), table_name='suppression_rules')
    op.drop_table('suppression_rules')
    # ### end Alembic commands ###
