"""add alert assignment and notes

Revision ID: 67040ba97a7a
Revises: 0b81611fb611
Create Date: 2026-05-20 22:24:37.700163
"""
from alembic import op
import sqlalchemy as sa



revision = '67040ba97a7a'
down_revision = '0b81611fb611'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_notes_alert_id'), 'alert_notes', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_notes_author'), 'alert_notes', ['author'], unique=False)
    op.add_column('alerts', sa.Column('assigned_to', sa.String(length=128), nullable=True))
    op.add_column('alerts', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_alerts_assigned_to'), 'alerts', ['assigned_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_assigned_to'), table_name='alerts')
    op.drop_column('alerts', 'assigned_at')
    op.drop_column('alerts', 'assigned_to')
    op.drop_index(op.f('ix_alert_notes_author'), table_name='alert_notes')
    op.drop_index(op.f('ix_alert_notes_alert_id'), table_name='alert_notes')
    op.drop_table('alert_notes')
    # ### end Alembic commands ###
